### ISSUE TITLE
Add docker image with shell to support CI systems that require shell (gitlab ci)

### ISSUE THREAD

**Issue by cvockrodt** [alcideio/skan#4]
As far as I can tell, no shell is available on the official docker image alcide/skan does not have a shell that can be used as an entrypoint

This makes using the official image with GitLab CI jobs impossible

The official kaniko image also doesn't have a shell, so the :debug tag is required for GitLab CI jobs since it has a shell. Could you offer something similar?

**Comment by gadinaor** [comment]
@cvockrodt yes - we can add that.

This is what we're using to build the current image:

```
FROM alpine:latest AS build
RUN  apk --no-cache --update add wget ca-certificates

FROM scratch

WORKDIR /
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY skan /skan

ENTRYPOINT  ["/skan"]
```

**Comment by gadinaor** [comment]
@cvockrodt can you please check if the debug docker image created for v0.6.1 address the issue you had with gitlab-ci?

`docker pull alcide/skan:v0.6.1-debug`

**Comment by cvockrodt** [comment]
This GitLab CI job definition is confirmed working

```
kube:lint:
  stage: test
  image:
    entrypoint: [""]
    name: alcide/skan:v0.6.1-debug
  script:
  - /skan manifest -o json --outputfile kube-skan.json -f kube/
  rules:
  - changes:
    - kube/
    when: always
  - when: manual
  artifacts:
    paths:
    - kube-skan.json
```

Is it safe to assume that there will be a "latest" equivalent for debug? i.e. alcide/skan:debug
